import random

import Tetromino

TETROMINOES = {'I': [['....',
                      '....',
                      'IIII',
                      '....'],
                     ['..I.',
                      '..I.',
                      '..I.',
                      '..I.']],
               'J': [['....',
                      '.J..',
                      '.JJJ',
                      '....'],
                     ['....',
                      '..JJ',
                      '..J.',
                      '..J.'],
                     ['....',
                      '....',
                      '.JJJ',
                      '...J'],
                     ['....',
                      '..J.',
                      '..J.',
                      '.JJ.']],
               'L': [['....',
                      '...L',
                      '.LLL',
                      '....'],
                     ['....',
                      '..L.',
                      '..L.',
                      '..LL'],
                     ['....',
                      '....',
                      '.LLL',
                      '.L..'],
                     ['....',
                      '.LL.',
                      '..L.',
                      '..L.']],
               'O': [['....',
                      '.OO.',
                      '.OO.',
                      '....']],
               'S': [['....',
                      '..SS',
                      '.SS.',
                      '....'],
                     ['....',
                      '.S..',
                      '.SS.',
                      '..S.']],
               'Z': [['....',
                      '.ZZ.',
                      '..ZZ',
                      '....'],
                     ['....',
                      '..Z.',
                      '.ZZ.',
                      '.Z..']],
               'T': [['....',
                      '..T.',
                      '.TTT',
                      '....'],
                     ['....',
                      '..T.',
                      '..TT',
                      '..T.'],
                     ['....',
                      '....',
                      '.TTT',
                      '..T.'],
                     ['....',
                      '..T.',
                      '.TT.',
                      '..T.']]}


class Randomizer:

    def __init__(self):
        self.bag = []

    def get_tetromino(self):
        if len(self.bag) == 0:
            self.bag = ['I', 'J', 'L', 'O', 'S', 'Z', 'T']
            random.shuffle(self.bag)
        return Tetromino.Tetromino(3, -1, 0, TETROMINOES[self.bag.pop()], 4)
